"""empty message

Revision ID: 4cef9aa8fe0a
Revises: 71cba9845d58
Create Date: 2024-06-03 13:50:41.480365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cef9aa8fe0a'
down_revision = '71cba9845d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp', sa.Integer(), nullable=True))

    with op.batch_alter_table('dailies', schema=None) as batch_op:
        batch_op.alter_column('repeats',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dailies', schema=None) as batch_op:
        batch_op.alter_column('repeats',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('exp')

    # ### end Alembic commands ###
